### PR TITLE
Add a couple of directories to index from the jk72 group

### PR DESCRIPTION
**Pull request by micaeljtoliveira**

### CODE REVIEW

**Comment by micaeljtoliveira** [comment]
@aekiss This adds the two directories that Paul requested.

**Comment by aidanheerdegen** [comment]
Just a note: if people don't have access to `jk72` they'll get a fairly useless error

https://github.com/COSIMA/cosima-cookbook/issues/293

Now I am sure I remember writing some instructions somewhere about what projects you'd need to be a member of to access all the data in the DB, but now I cannot find it, which sounds to me like it needs to be written somewhere.

**Review by aekiss — DISMISSED** [review]
LGTM - thanks Micael

**Comment by micaeljtoliveira** [comment]
@aekiss FIY: I'm waiting for the DB nightly update to finish successfully before merging this.

**Pull request merged**
